### ISSUE TITLE
Errors While Creating Dataset

### ISSUE THREAD

**Issue by fahdmirza** [argilla-io/synthetic-data-generator#14]
Hi,
 On my ubuntu system, gradio demo launches but when I try to create dataset for chat, after giving description, clicking on Create  button give error:

`home/Ubuntu/mycode/syndatagen/synthetic-data-generator/src/synthetic_dataset_generator/constants.py:60: UserWarning: ARGILLA_API_URL or ARGILLA_API_KEY is not set
  warnings.warn("ARGILLA_API_URL or ARGILLA_API_KEY is not set")
/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/oauth.py:163: UserWarning: Gradio does not support OAuth features outside of a Space environment. To help you debug your app locally, the login and logout buttons are mocked with your profile. To make it work, your machine must be logged in to Huggingface.
  warnings.warn(
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/components/login_button.py:75: UserWarning: LoginButton created outside of a Blocks context. May not work unless you call its `activate()` method manually.
  warnings.warn(
/home/Ubuntu/mycode/syndatagen/synthetic-data-generator/src/synthetic_dataset_generator/__init__.py:28: UserWarning: Since the `base_url=https://api-inference.huggingface.co/v1/` is available and either one of `model_id` or `endpoint_name` is also provided, the `base_url` will either be ignored or overwritten with the one generated from either of those args, for serverless or dedicated inference endpoints, respectively.
  warnings.warn(  # type: ignore
Step 'None' hasn't received a pipeline, and it hasn't been created within a `Pipeline` context. Please, use `with Pipeline() as pipeline:` and create the step within the context.
/home/Ubuntu/mycode/syndatagen/synthetic-data-generator/src/synthetic_dataset_generator/__init__.py:28: UserWarning: Since the `base_url=https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-8B-Instruct` is available and either one of `model_id` or `endpoint_name` is also provided, the `base_url` will either be ignored or overwritten with the one generated from either of those args, for serverless or dedicated inference endpoints, respectively.
  warnings.warn(  # type: ignore
⚠️ Received no response using Inference Client (model: 'meta-llama/Meta-Llama-3.1-8B-Instruct'). Finish reason was: 400, message='Bad Request', url='https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-8B-Instruct'
Step 'None' hasn't received a pipeline, and it hasn't been created within a `Pipeline` context. Please, use `with Pipeline() as pipeline:` and create the step within the context.
Step 'None' hasn't received a pipeline, and it hasn't been created within a `Pipeline` context. Please, use `with Pipeline() as pipeline:` and create the step within the context.
Step 'None' hasn't received a pipeline, and it hasn't been created within a `Pipeline` context. Please, use `with Pipeline() as pipeline:` and create the step within the context.
Traceback (most recent call last):
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/blocks.py", line 2047, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/gradio/utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/mycode/syndatagen/synthetic-data-generator/src/synthetic_dataset_generator/apps/chat.py", line 80, in generate_sample_dataset
    dataframe = generate_dataset(
                ^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/mycode/syndatagen/synthetic-data-generator/src/synthetic_dataset_generator/apps/chat.py", line 141, in generate_dataset
    batch = list(magpie_generator.process(inputs=inputs))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/distilabel/steps/tasks/magpie/base.py", line 568, in process
    yield self._generate_with_pre_query_template(inputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/distilabel/steps/tasks/magpie/base.py", line 318, in _generate_with_pre_query_template
    self._generate_instruction(inputs)
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/distilabel/steps/tasks/magpie/base.py", line 190, in _generate_instruction
    outputs = self.llm.generate(
              ^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/distilabel/llms/base.py", line 492, in generate
    return self.event_loop.run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/distilabel/llms/base.py", line 469, in _agenerate
    outputs = [outputs[0] for outputs in await asyncio.gather(*tasks)]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py", line 33, in wrapper_function
    return await wrapper(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/miniconda3/envs/ai/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py", line 111, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 3 validation errors for InferenceEndpointsLLM.agenerate
input.list[typed-dict].0.content
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
input.tuple[list[typed-dict], nullable[union[typed-dict,typed-dict]]].0
  Input should be a valid list [type=list_type, input_value={'role': 'system', 'content': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/list_type
input.tuple[list[typed-dict], nullable[union[typed-dict,typed-dict]]].1
  Field required [type=missing, input_value=[{'role': 'system', 'content': None}], input_type=list]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
^CKeyboard interruption in main thread... closing server.

`

**Comment by davidberenstein1957** [comment]
Hi @fahdmirza, I would love to help you get setup. 

> ⚠️ Received no response using Inference Client (model: 'meta-llama/Meta-Llama-3.1-8B-Instruct'). Finish reason was: 400, message='Bad Request', url='https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-8B-Instruct

It seems that the request to the inference endpoints is wrong. Are you forwarding all the required information? I think from our side we need to add some validation for passing invalid fields. Could you perhaps record a video of what is going wrong, while you follow this approach? https://www.youtube.com/watch?v=nXjVtnGeEss

**Comment by fahdmirza** [comment]
Hi @davidberenstein1957 ,
  Thanks for your help. I am also trying to create a video around it for my channel at https://www.youtube.com/@fahdmirza

Following are the steps I am running:

conda create -n ai python=3.11 -y && conda activate ai

pip install synthetic-dataset-generator

git clone https://github.com/argilla-io/synthetic-data-generator.git && cd synthetic-data-generator

pip install -e .

export HF_TOKEN=<>
export BASE_URL=http://localhost:11434
export MODEL=llama3.2:latest

huggingface-cli login

python app.py

http://localhost:7860

regards,
Fahd

**Comment by davidberenstein1957** [comment]
Hi @fahdmirza which version are you currently using? I think I might have resolved this issue in the latest release?

**Comment by fahdmirza** [comment]
Hi,
 I am using the latest version. I have tried it following your ReadMe. I have spent like 5 hours today and its still not working. I have tried it with HF inference endpoint, Open ai model, ollama but nothing works. I have installed it with pip , from source but in vain. I have also checked other threads here and I see similar errors. 

My suggestion is first just try to make it work with HF inference endpoint because I believe it only is geared towards that endpoint. Please advise in ReadMe, what token do we need? Is this a paid option at HuggingFace? 

I followed for example the following from your ReadMe:

You can simply install the package with:
pip install synthetic-dataset-generator
from synthetic_dataset_generator import launch
launch()

It launches gradio demo, and when we try to create Chat dataset after logging into huggingface, it throws following error:


Serverless or dedicated inference endpoints, respectively.
  warnings.warn(  # type: ignore
tokenizer_config.json: 100%|████████████████████████████████████████| 55.4k/55.4k [00:00<00:00, 2.63MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████| 9.09M/9.09M [00:00<00:00, 38.4MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████| 296/296 [00:00<00:00, 1.59MB/s]
⚠️ Received no response using Inference Client (model: 'meta-llama/Meta-Llama-3.1-8B-Instruct'). Finish reason was: 400, message='Bad Request', url='https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-8B-Instruct'

**Comment by davidberenstein1957** [comment]
Hi,Thanks for your perseverance. I think you might be using a Hugging Face token that is not allowed to call the inference endpoints? Or your account does not have access to the model. It is a gates repo so you first need to accept the terms of service for that specific model. I will record a short video on how to do custom deployments. Cheers,David On 20 Dec 2024, at 04:54, Fahd Mirza ***@***.***> wrote:﻿
Hi,
I am using the latest version. I have tried it following your ReadMe. I have spent like 5 hours today and its still not working. I have tried it with HF inference endpoint, Open ai model, ollama but nothing works. I have installed it with pip , from source but in vain. I have also checked other threads here and I see similar errors.
My suggestion is first just try to make it work with HF inference endpoint because I believe it only is geared towards that endpoint. Please advise in ReadMe, what token do we need? Is this a paid option at HuggingFace?
I followed for example the following from your ReadMe:
You can simply install the package with:
pip install synthetic-dataset-generator
from synthetic_dataset_generator import launch
launch()
It launches gradio demo, and when we try to create Chat dataset after logging into huggingface, it throws following error:
Serverless or dedicated inference endpoints, respectively.
warnings.warn(  # type: ignore
tokenizer_config.json: 100%|████████████████████████████████████████| 55.4k/55.4k [00:00<00:00, 2.63MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████| 9.09M/9.09M [00:00<00:00, 38.4MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████| 296/296 [00:00<00:00, 1.59MB/s]
⚠️ Received no response using Inference Client (model: 'meta-llama/Meta-Llama-3.1-8B-Instruct'). Finish reason was: 400, message='Bad Request', url='https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-8B-Instruct'

**Comment by fahdmirza** [comment]
Hi David,
  I already have access to the gated model. I have tried with Read and Write token but in vain. Is there any other token I need? Is this a paid option? My suggestion is that instead of inference endpoint, it would be good idea to use local models such as ollama etc with this tool. Thanks.

**Comment by cuba6112** [comment]
I am having the same issue and I have access in hugging face to llama3.1, using pop os.

 Received no response using Inference Client (model: 'meta-llama/Meta-Llama-3.1-8B-Instruct'). Finish reason was: 400, message='Bad Request', url='https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3.1-8B-Instruct'

**Comment by davidberenstein1957** [comment]
@fahdmirza @cuba6112 you ca try to deploy it locally with this PR. https://github.com/argilla-io/synthetic-data-generator/pull/20 the example using ollama should work for local deployments. https://github.com/argilla-io/synthetic-data-generator/blob/feat/improve-support-local-deployment/examples/ollama_deployment.py

**Comment by cuba6112** [comment]
Hi David, I tried with ollama but only the classification data generation works. The chat does not.

**Comment by mlaprise** [comment]
I have a similar issue where I can't generate chat data with Ollama endpoint. I have a endpoint running locally and the following configuration:


import os

from synthetic_dataset_generator import launch

# os.environ["HF_TOKEN"] = "hf_..."  # push the data to huggingface
os.environ["OLLAMA_BASE_URL"] = "http://127.0.0.1:11434/"  # ollama base url
os.environ["MODEL"] = "llama3.1:8b"  # model id

launch()

I get the following error:
huggingface_hub.errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://api-inference.huggingface.co/status/llama3.1:8b (Request ID: HqVfRe21Bg8QlKEhjljdT)

Is there a way to only use the Ollama endpoint ?

**Comment by cuba6112** [comment]
Ollama will not work, read the magpie paper.. They use the schema used to train llama so when they pass the schema empty to the model it respond with good synthethic data. However ollama has wrapper with instructions and this mess up the synthetic data.. You have to use VLLm.

**Comment by davidberenstein1957** [comment]
Hi @mlaprise @cuba6112, the following code should work but relies on 2 PRs to be merged: a [PR in distilabel](https://github.com/argilla-io/distilabel/pull/1086) and a [PR in this repo](https://github.com/argilla-io/synthetic-data-generator/pull/20). Waiting for people to get back from holidays to wrap this up.

First, install the branch. Recommended in a virtual environment.

```bash
pip install git+https://github.com/argilla-io/synthetic-data-generator.git@feat/improve-support-local-deployment
```

Run a qwen or llama3 model with ollama.

```bash
ollama serve
ollama run qwen2.5:32b-instruct-q5_K_S
```

Could you run the following code.

```python 
import os

from synthetic_dataset_generator import launch

# os.environ["HF_TOKEN"] = "hf_..."  # push the data to huggingface
os.environ["OLLAMA_BASE_URL"] = "http://127.0.0.1:11434/"  # ollama base url
os.environ["MODEL"] = "qwen2.5:32b-instruct-q5_K_S"  # model id
os.environ["TOKENIZER_ID"] = "Qwen/Qwen2.5-32B-Instruct"  # tokenizer id
os.environ["MAGPIE_PRE_QUERY_TEMPLATE"] = "qwen2"
os.environ["MAX_NUM_ROWS"] = "10000"
os.environ["DEFAULT_BATCH_SIZE"] = "2"
os.environ["MAX_NUM_TOKENS"] = "1024"

launch()
```

@cuba6112 within ollama you can pre-format data yourself and then pass the `raw=True` argument to the completion call, which will generate without internally applying the chat template, allowing for the usage of magpie in a similar way as vLLM. 

@cuba6112 If you want, you can add a PR with examples of vLLM. I will also have a brief look at this.

**Comment by davidberenstein1957** [comment]
@cuba6112 @mlaprise @fahdmirza this was solved in #20

**Comment by cuba6112** [comment]
Thank you!
